#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pyelftools
Version  : 0.27
Release  : 13
URL      : https://files.pythonhosted.org/packages/6b/b5/f7022f2d950327ba970ec85fb8f85c79244031092c129b6f34ab17514ae0/pyelftools-0.27.tar.gz
Source0  : https://files.pythonhosted.org/packages/6b/b5/f7022f2d950327ba970ec85fb8f85c79244031092c129b6f34ab17514ae0/pyelftools-0.27.tar.gz
Summary  : Library for analyzing ELF files and DWARF debugging information
Group    : Development/Tools
License  : Unlicense
Requires: pyelftools-bin = %{version}-%{release}
Requires: pyelftools-license = %{version}-%{release}
Requires: pyelftools-python = %{version}-%{release}
Requires: pyelftools-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3
BuildRequires : pluggy
BuildRequires : py-python
BuildRequires : pytest
BuildRequires : tox
BuildRequires : virtualenv

%description
==========
pyelftools
==========
.. image:: https://github.com/eliben/pyelftools/workflows/pyelftools-tests/badge.svg
:align: center
:target: https://github.com/eliben/pyelftools/actions

%package bin
Summary: bin components for the pyelftools package.
Group: Binaries
Requires: pyelftools-license = %{version}-%{release}

%description bin
bin components for the pyelftools package.


%package license
Summary: license components for the pyelftools package.
Group: Default

%description license
license components for the pyelftools package.


%package python
Summary: python components for the pyelftools package.
Group: Default
Requires: pyelftools-python3 = %{version}-%{release}

%description python
python components for the pyelftools package.


%package python3
Summary: python3 components for the pyelftools package.
Group: Default
Requires: python3-core
Provides: pypi(pyelftools)

%description python3
python3 components for the pyelftools package.


%prep
%setup -q -n pyelftools-0.27
cd %{_builddir}/pyelftools-0.27

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1603812177
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pyelftools
cp %{_builddir}/pyelftools-0.27/LICENSE %{buildroot}/usr/share/package-licenses/pyelftools/29a06f5b461ea380819c2914ac77ebcc6069a79b
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/readelf.py

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pyelftools/29a06f5b461ea380819c2914ac77ebcc6069a79b

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
